Relationships
shella12/OOP-school-library pull request #3
Opened 2023-02-16 13:06 UTC by shella12

In this project, I finished creating the remaining classes for the oop school library and created the associations between them.

Following changes were made:

Create a class Classroom with the following:
@label instance variable, should be initialized in the constructor.
Setter and getter for @label (remember about attr_accessor).
Create the has-many/belongs-to relationship between Classroom and Student. The following should be implemented:
Create the has-many side (a classroom has many students).
Create the belongs-to side (a student belongs to a classroom).
Make sure that when adding a student to a classroom it also sets the classroom for the student.
Make sure that when setting the classroom for a student it also adds it to the classrooms' students.
Create a class Book with the following:
@title and @author instance variables, should be initialized in the constructor.
Setters and getters for instance variables (remember about attr_accessor).
Create a class Rental with the following:
@date instance variable, should be initialized in the constructor.
Setter and getter for @date (remember about attr_accessor).
Create the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental. The following should be implemented:
Create the has-many side of Book and Rental (a book has many rentals).
Create the belongs-to side of Rental and Book (a rental belongs to a book).
Create the has-many side of Person and Rental (a person has many rentals).
Create the belongs-to side of Rental and Person (a rental belongs to a person).
Modify the constructor of Rental so Book and Person are set in it.

2023-02-16 14:46 UTC, FrederickMih requested changes
## Hi 🙋 @shella12   , 


Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![](https://media.giphy.com/media/nYYtQdLqwwlTe3ccKh/giphy.gif)

## Highlights 🟢 🟢 🟢 


- PR is professional ✔️ 
- Linters checks passed ✔️


## Required Changes ♻️

- [ ] **README.md** Let's kindly make sure to customize the license file. 

![Capture](https://user-images.githubusercontent.com/63087491/219396810-88fc60e1-6b36-46a7-b05c-6e06168c5fcb.PNG)


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 14:46 UTC, FrederickMih commented on book.rb
> +  attr_reader :rents
- [ ] rents variable can also be modified hence let kindly use Setters and Getters(attr_accessor)

2023-02-16 14:46 UTC, FrederickMih commented on book.rb
> +  end
- [ ] I think this method should actually create a new rental. A person on a particular date should be able to create a rental for a book. Let's kindly try doing it this way.

 ```.ruby
 def add_rents(person, date)
    Rental.new(date, self, person) # book itself should be sent as a parameter('has-many' associations)
 end
```

2023-02-16 14:46 UTC, FrederickMih commented on rental.rb
> +  attr_reader :student, :book, :person
- [ ] Let's kindly make sure that a book and a person should be modified(`attr_accessor :date, :book, :person`) 👍

2023-02-16 14:46 UTC, FrederickMih commented on rental.rb
> +    book.rents << self
A rental belongs to a book. This is great 👍

2023-02-16 14:46 UTC, FrederickMih commented on person.rb
> +  end
- [ ] Let's kindly check out the comment above ⬆️ and modify this method accordingly

2023-02-17 11:15 UTC, ichala requested changes
Hi Student
Good job so far! 
👏👏👏 
You still need to work on some issues to go to the next project, but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- No Linter errors  ✔️
-  All The technical requirements implemented ✔️


 ## Required Changes ♻️

- [ ] **_🛑 as mentioned by the previous reviewer kindly update your Licence information 🙏 _**






## Optional suggestions

- N/A

**********
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 11:36 UTC, t-yanick approved these changes
# STATUS: MILESTONE APPROVED 👍 

Hi @shella12 , 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  All changes by previous reviewers implemented
:heavy_check_mark: Descriptive Readme file and PR

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 12:32 UTC, merged